version: '3.7'

services:
  bitwarden:
    restart: unless-stopped
    image: vaultwarden/server:latest
    container_name: bitwarden
    volumes:
      - ${LOCAL_DATA_DIR}:/data
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      DOMAIN: https://${HOST}
      INVITATIONS_ALLOWED: ${INVITATIONS_ALLOWED}
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURITY: ${SMTP_SECURITY}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    networks:
      - traefik
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.bitwarden-ui.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-ui.rule=Host(`${HOST}`)"
      - "traefik.http.routers.bitwarden-ui.middlewares=default@file"
      - "traefik.http.routers.bitwarden-ui.tls=true"
      - "traefik.http.routers.bitwarden-ui.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.bitwarden-ui.service=bitwarden-ui"
      - "traefik.http.services.bitwarden-ui.loadbalancer.server.port=80"
      - "traefik.http.routers.bitwarden-websocket.rule=Host(`${HOST}`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-websocket.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-websocket.tls=true"
      - "traefik.http.routers.bitwarden-websocket.middlewares=default@file,bitwarden-strip-prefix@file"
      - "traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket"
      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"

  bitwarden-backup:
    depends_on:
      - bitwarden
    build:
      context: ./backup
      dockerfile: Dockerfile
      args:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${GOOGLE_SERVICE_ACCOUNT_JSON}
    image: bitwarden-backup:latest
    container_name: bitwarden-backup
    restart: unless-stopped
    volumes:
      - ${LOCAL_DATA_DIR}:/bitwarden
    environment:
      BACKUP_ENCRYPTION_KEY: ${BACKUP_ENCRYPTION_KEY}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${GOOGLE_SERVICE_ACCOUNT_JSON}
      TZ: "Europe/Zurich"

networks:
  traefik:
    external: true
