version: '3.7'

services:
  bitwarden:
    restart: unless-stopped
    image: vaultwarden/server:latest
    container_name: bitwarden
    volumes:
      - ${LOCAL_DATA_DIR}:/data
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      DOMAIN: https://${HOST}
      INVITATIONS_ALLOWED: 'true'
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'false' # set to false to disable signups
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SSL: ${SMTP_SSL}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    networks:
      - traefik
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.middlewares.bitwarden-https-redirect.redirectScheme.scheme=https"
      - "traefik.http.middlewares.bitwarden-https-redirect.redirectScheme.permanent=true"
      - "traefik.http.routers.bitwarden-ui-https.rule=Host(`${HOST}`)"
      - "traefik.http.routers.bitwarden-ui-https.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-ui-https.tls=true"
      - "traefik.http.routers.bitwarden-ui-https.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.bitwarden-ui-https.service=bitwarden-ui"
      - "traefik.http.routers.bitwarden-ui-http.rule=Host(`${HOST}`)"
      - "traefik.http.routers.bitwarden-ui-http.entrypoints=web"
      - "traefik.http.routers.bitwarden-ui-http.middlewares=bitwarden-https-redirect"
      - "traefik.http.routers.bitwarden-ui-http.service=bitwarden-ui"
      - "traefik.http.services.bitwarden-ui.loadbalancer.server.port=80"
      - "traefik.http.routers.bitwarden-websocket-https.rule=Host(`${HOST}`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-websocket-https.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-websocket-https.tls=true"
      - "traefik.http.routers.bitwarden-websocket-https.service=bitwarden-websocket"
      - "traefik.http.routers.bitwarden-websocket-https.middlewares=bitwarden-geoblock"
      - "traefik.http.routers.bitwarden-websocket-http.rule=Host(`${HOST}`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-websocket-http.entrypoints=web"
      - "traefik.http.routers.bitwarden-websocket-http.middlewares=bitwarden-https-redirect"
      - "traefik.http.routers.bitwarden-websocket-http.service=bitwarden-websocket"
      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"
      # GeoBlock
      - "traefik.http.middlewares.bitwarden-geoblock.plugin.geoblock.allowlocalrequests=true"
      - "traefik.http.middlewares.bitwarden-geoblock.plugin.geoblock.allowunknowncountries=false"
      - "traefik.http.middlewares.bitwarden-geoblock.plugin.geoblock.api=https://get.geojs.io/v1/ip/country/{ip}"
      - "traefik.http.middlewares.bitwarden-geoblock.plugin.geoblock.cachesize=32"
      - "traefik.http.middlewares.bitwarden-geoblock.plugin.geoblock.countries=${ALLOWED_COUNTRIES}"
      - "traefik.http.middlewares.bitwarden-geoblock.plugin.geoblock.forcemonthlyupdate=true"
      - "traefik.http.middlewares.bitwarden-geoblock.plugin.geoblock.logallowedrequests=false"
      - "traefik.http.middlewares.bitwarden-geoblock.plugin.geoblock.logapirequests=true"
      - "traefik.http.middlewares.bitwarden-geoblock.plugin.geoblock.loglocalrequests=false"
      - "traefik.http.middlewares.bitwarden-geoblock.plugin.geoblock.unknowncountryapiresponse=nil"
      - "traefik.http.routers.bitwarden-ui-https.middlewares=bitwarden-geoblock"

  bitwarden-backup:
    depends_on:
      - bitwarden
    build:
      context: ./backup
      dockerfile: Dockerfile
      args:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${GOOGLE_SERVICE_ACCOUNT_JSON}
    image: bitwarden-backup:latest
    container_name: bitwarden-backup
    restart: unless-stopped
    volumes:
      - ${LOCAL_DATA_DIR}:/bitwarden
    environment:
      BACKUP_ENCRYPTION_KEY: ${BACKUP_ENCRYPTION_KEY}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${GOOGLE_SERVICE_ACCOUNT_JSON}
      TZ: "Europe/Zurich"

networks:
  traefik:
    external: true
