version: '3.7'

services:
  pihole:
    restart: unless-stopped
    image: pihole/pihole:latest
    container_name: pihole
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
    environment:
      ServerIP: ${SERVER_IP}
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: ${HOST}
      TZ: ${TIME_ZONE}
      WEBPASSWORD: ${WEB_PASSWORD}
      WEB_PORT: 9000
    networks:
      - traefik
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.rule=Host(`${HOST}`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.pihole.middlewares=default@file"
      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.services.pihole.loadbalancer.server.port=9000"
    volumes:
      - ${LOCAL_DATA_DIR}/etc-pihole:/etc/pihole
      - ${LOCAL_DATA_DIR}/etc-dnsmasqd:/etc/dnsmasq.d
      - ${LOCAL_DATA_DIR}/pihole.log:/var/log/pihole.log

networks:
  traefik:
    external: true
