version: '3.7'

networks:
  traefik:
    external: true

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: always
    networks:
      - traefik
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`${HOST}`)"
      - "traefik.http.routers.traefik.middlewares=traefikAuth@file,default@file"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.sticky.cookie.httpOnly=true"
      - "traefik.http.services.traefik.loadbalancer.sticky.cookie.secure=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LOCAL_CONF_DIR}/acme.json:/letsencrypt/acme.json
      - ${LOCAL_DATA_DIR}/tmp:/tmp
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic-configuration.yml:/dynamic-configuration.yml:ro
      - /var/traefik/log:/var/log/traefik

  hub-agent:
    image: ghcr.io/traefik/hub-agent-traefik:v1.0.1
    container_name: hub-agent
    restart: always
    command:
      - run
      - --hub.token=${HUB_TOKEN}
      - --auth-server.advertise-url=http://hub-agent
      - --traefik.host=traefik
      - --traefik.tls.insecure=true
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - traefik
