tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true

http:
  middlewares:
    traefikAuth:
      basicAuth:
        users:
          - username:password-hash

    default:
      chain:
        middlewares:
          - default-security-headers
          - gzip
          - geo-block

    default-security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        frameDeny: true
        #       Deprecated
        #       sslRedirect: true
        #HSTS Configuration
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"

    gzip:
      compress: {}

    geo-block:
      plugin:
        geoblock:
          allowLocalRequests: true
          allowUnknownCountries: false
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          apiTimeoutMs: 750
          cachesize: 32
          countries: [DE, AT]
          forceMonthlyUpdate: true
          logAllowedRequests: false
          logApiRequests: true
          logLocalRequests: false
          unknownCountryApiResponse: nil

    bitwarden-strip-prefix:
      stripPrefix:
        prefixes:
          - "/notifications/hub"
        forceSlash: false

    nextcloud-caldav:
      replacePathRegex:
        regex: "^/.well-known/ca(l|rd)dav"
        replacement: "/remote.php/dav/"

    crowdsec-bouncer:
      forwardAuth:
        address: http://crowdsec-bouncer-traefik:8080/api/v1/forwardAuth
        trustForwardHeader: true
