[log]
  level = "INFO"

[providers.docker]
  exposedByDefault = false

[api]
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.dashboard]
    address = ":8080"

[certificatesResolvers.myhttpchallenge.acme]
    email = "samuel.bachmann@gmail.com"
    storage = "acme.json"
    [certificatesResolvers.myhttpchallenge.acme.httpChallenge]
        entrypoint = "web"
    #[certificatesResolvers.myhttpchallenge.acme.tlsChallenge]

[http.routers.api]
  rule = "Host(`traefik.samuel.cloud`)"
  service = "api@internal"
  middlewares = ["auth"]

[http.middlewares.auth.digestAuth]
  users = [
    "sam:traefik:2968ccdaaaa9d303f330a97830cd48e8",
  ]

# Redirect to https
[http.middlewares]
  [http.middlewares.test-redirectscheme.redirectScheme]
    scheme = "https"
    permanent = true
