global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  debug: true

log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

providers:
  docker:
    exposedByDefault: false
  file:
    filename: "./dynamic-configuration.yml"
    watch: true
  providersThrottleDuration: 10s

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"
    http:
      middlewares:
        - crowdsec-bouncer@file

certificatesResolvers:
  myhttpchallenge:
    acme:
      email: "user@example.com"
      storage: "/letsencrypt/acme.json"
      tlsChallenge: {}
      # httpChallenge:
      #   entryPoint: "web"

experimental:
  hub: true

  plugins:
    geoblock:
      moduleName: "github.com/PascalMinder/geoblock"
      version: "v0.2.3"

hub:
  tls:
    insecure: true

metrics:
  prometheus:
    addRoutersLabels: true
