version: '3.7'

services:
  portainer:
    restart: unless-stopped
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      - traefik
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`${HOST}`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.portainer.middlewares=default@file"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    volumes:
      - ${LOCAL_DATA_DIR}:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik:
    external: true
