version: '3.7'

services:
  portainer:
    restart: unless-stopped
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      - traefik
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.rule=Host(`${HOST}`)"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-secure.rule=Host(`${HOST}`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.routers.portainer-secure.middlewares=portainer-geoblock"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik"
      # GeoBlock
      - "traefik.http.middlewares.portainer-geoblock.plugin.geoblock.allowlocalrequests=true"
      - "traefik.http.middlewares.portainer-geoblock.plugin.geoblock.allowunknowncountries=false"
      - "traefik.http.middlewares.portainer-geoblock.plugin.geoblock.api=https://get.geojs.io/v1/ip/country/{ip}"
      - "traefik.http.middlewares.portainer-geoblock.plugin.geoblock.cachesize=32"
      - "traefik.http.middlewares.portainer-geoblock.plugin.geoblock.countries=${ALLOWED_COUNTRIES}"
      - "traefik.http.middlewares.portainer-geoblock.plugin.geoblock.forcemonthlyupdate=true"
      - "traefik.http.middlewares.portainer-geoblock.plugin.geoblock.logallowedrequests=false"
      - "traefik.http.middlewares.portainer-geoblock.plugin.geoblock.logapirequests=true"
      - "traefik.http.middlewares.portainer-geoblock.plugin.geoblock.loglocalrequests=false"
      - "traefik.http.middlewares.portainer-geoblock.plugin.geoblock.unknowncountryapiresponse=nil"
    volumes:
      - ${LOCAL_DATA_DIR}:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik:
    external: true
