version: '3.7'

services:
  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec:latest
    restart: unless-stopped
    hostname: crowdsec
    environment:
      PGID: "1000"
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/base-http-scenarios crowdsecurity/http-cve crowdsecurity/sshd crowdsecurity/nextcloud Dominic-Wagner/vaultwarden crowdsecurity/whitelist-good-actors"
    networks:
      traefik:
        ipv4_address: 172.29.0.7
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./mywhitelists.yaml:/etc/crowdsec/parsers/s02-enrich/mywhitelists.yaml
      - ${LOCAL_CROWDSEC_CONFIG_DIR}:/etc/crowdsec
      - ${LOCAL_CROWDSEC_DATA_DIR}:/var/lib/crowdsec/data
      # Logs.
      - /var/log/:/var/log/:ro
      - /var/traefik/log/:/var/traefik/log/:ro
      - ${LOCAL_CROWDSEC_NEXTCLOUD_LOG}:/var/nextcloud/log/nextcloud.log:ro
      - ${LOCAL_CROWDSEC_VAULTWARDEN_LOG}:/var/vaultwarden/log/vaultwarden.log:ro
    security_opt:
      - no-new-privileges=true

  crowdsec-bouncer-traefik:
    container_name: crowdsec-bouncer-traefik
    image: fbonalair/traefik-crowdsec-bouncer:latest
    restart: unless-stopped
    hostname: crowdsec-bouncer-traefik
    environment:
      CROWDSEC_BOUNCER_API_KEY: ${TRAEFIK_BOUNCER_KEY}
      CROWDSEC_AGENT_HOST: crowdsec:8080
      CROWDSEC_BOUNCER_SCHEME: http
      CROWDSEC_BOUNCER_LOG_LEVEL: 1
      CROWDSEC_BOUNCER_BAN_RESPONSE_MSG: Forbidden
      GIN_MODE: release
      PORT: 8080
    depends_on:
      - crowdsec
    networks:
      traefik:
        ipv4_address: 172.29.0.8

#  crowdsec-blocklist-mirror:
#    container_name: crowdsec-blocklist-mirror
#    image: crowdsecurity/blocklist-mirror
#    restart: unless-stopped
#    hostname: crowdsec-blocklist-mirror
#    ports:
#      - "41412:41412"
#    volumes:
#      - ./blocklist-mirror-conf.yaml:/etc/crowdsec/bouncers/crowdsec-blocklist-mirror.yaml
#    depends_on:
#      - crowdsec
#    networks:
#      - traefik

networks:
  traefik:
    external: true
